- platform: template
  sensors:
    washmachine:
        friendly_name: "Washing Machine"
        icon_template: mdi:washing-machine
        delay_off:
          minutes: 5
        value_template: >-
          {{ states('sensor.fibaro_system_fgwpe_f_wall_plug_gen5_power') | float > 2.0 }}
    door_back:
      value_template: "{{ is_state('sensor.fibaro_system_fgdw002_door_opening_sensor_2_access_control', '22') }}"
      device_class: opening
      friendly_name: Back Door
      icon_template: mdi:door
    
