- platform: darksky
  api_key: !secret darksky_key
  name: Weather
  language: fr
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - precip_type
    - precip_probability
    - temperature
    - apparent_temperature
    - dew_point
    - humidity
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_max
    - temperature_min
- platform: speedtest
  minute: 30
  hour:
    - 0
    - 6
    - 12
    - 18
  monitored_conditions:
    - ping
    - download
    - upload
- platform: nest
  monitored_conditions:
    - 'battery_level'
    - 'co_status'
    - 'smoke_status'
- platform: google_wifi
- platform: transmission
  host: !secret rpi_ip
  port: 9091
  username: !secret transmission_user
  password: !secret transmission_pass
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'
    - 'active_torrents'
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_use_percent
    - type: ipv4_address
      arg: eth0
    - type: processor_use
    - type: last_boot
    - type: since_last_boot
- platform: mqtt
  state_topic: !secret owntrack_queue_marco
  name: "Battery Asus Marco"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'
  device_class: battery
- platform: tcp
  name: Plex Internal HD
  host: !secret plex_ip
  port: !secret plex_port
  timeout: 5
  payload: "\n"
  value_template: "{{ value.split('|')[3] }}"
  unit_of_measurement: "°C"
- platform: tcp
  name: Plex External HD
  host: !secret plex_ip
  port: !secret plex_port
  timeout: 5
  payload: "\n"
  value_template: "{{ value.split('|')[8] }}"
  unit_of_measurement: "°C"
