- platform: darksky
  api_key: !secret darksky_key
  name: Weather
  language: fr
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - precip_type
    - precip_probability
    - temperature
    - apparent_temperature
    - dew_point
    - humidity
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_max
    - temperature_min
- platform: nest
  monitored_conditions:
    - 'battery_level'
    - 'co_status'
    - 'smoke_status'
- platform: google_wifi
- platform: rest
  name: Toilette Temperature
  resource: !secret toilette_temp_sensor
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: °C
