- platform: darksky
  api_key: !secret darksky_key
  name: Weather
  language: fr
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - precip_type
    - precip_probability
    - temperature
    - apparent_temperature
    - dew_point
    - humidity
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_max
    - temperature_min
- platform: speedtest
  minute: 30
  hour:
    - 0
    - 6
    - 12
    - 18
  monitored_conditions:
    - ping
    - download
    - upload
- platform: nest
  monitored_conditions:
    - 'battery_level'
    - 'co_status'
    - 'smoke_status'
- platform: google_wifi
- platform: transmission
  host: !secret rpi_ip
  port: 9091
  username: !secret transmission_user
  password: !secret transmission_pass
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'
    - 'active_torrents'
    - 'paused_torrents'
    - 'total_torrents'
- platform: tcp
  name: Plex Internal HD
  host: 192.168.0.24
  port: 7634
  timeout: 5
  payload: "\n"
  value_template: "{{ value.split('|')[3] }}"
  unit_of_measurement: "°C"
- platform: tcp
  name: Plex External HD
  host: 192.168.0.24
  port: 7634
  timeout: 5
  payload: "\n"
  value_template: "{{ value.split('|')[8] }}"
  unit_of_measurement: "°C"
- platform: rest
  name: Toilette Temperature
  resource: !secret toilette_temp_sensor
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: °C
